all:
	g++ platform.cpp -o platform -O2
	g++ agent1.cpp -o agent1 -O2
	g++ agent2.cpp -o agent2 -O2
	g++ learn1.cpp -o learn1 -O2
	g++ learn2.cpp -o learn2 -O2

clean:
	rm platform
	rm agent1
	rm agent2
	rm learn1
	rm learn2
	rm helper*
	rm result*
