all:
	g++ platform.cpp -o platform -O2
	g++ agent1.cpp -o agent1 -O2
	g++ agent2.cpp -o agent2 -O2
	g++ agent3.cpp -o agent3 -O2
	g++ agent4.cpp -o agent4 -O2
	g++ agent5.cpp -o agent5 -O2
	g++ agent6.cpp -o agent6 -O2
	g++ agent7.cpp -o agent7 -O2
	g++ agent8.cpp -o agent8 -O2
	g++ agent9.cpp -o agent9 -O2
	g++ agent10.cpp -o agent10 -O2
	g++ learn1.cpp -o learn1 -O2
	g++ learn2.cpp -o learn2 -O2
	g++ learn3.cpp -o learn3 -O2
	g++ learn4.cpp -o learn4 -O2
	g++ learn5.cpp -o learn5 -O2
	g++ learn6.cpp -o learn6 -O2
	g++ learn7.cpp -o learn7 -O2
	g++ learn8.cpp -o learn8 -O2
	g++ learn9.cpp -o learn9 -O2
	g++ learn10.cpp -o learn10 -O2

clean:
	rm platform
	rm agent1
	rm agent2
	rm agent3
	rm agent4
	rm agent5
	rm agent6
	rm agent7
	rm agent8
	rm agent9
	rm agent10
	rm learn1
	rm learn2
	rm learn3
	rm learn4
	rm learn5
	rm learn6
	rm learn7
	rm learn8
	rm learn9
	rm learn10
	rm helper*
	rm result*
