all:
	g++ platform.cpp -o platform -O2
	g++ agent1.cpp -o agent1 -O2
	g++ agent2.cpp -o agent2 -O2
	g++ agent3.cpp -o agent3 -O2
	g++ agent4.cpp -o agent4 -O2
	g++ agent5.cpp -o agent5 -O2
	g++ learn1.cpp -o learn1 -O2
	g++ learn2.cpp -o learn2 -O2
	g++ learn3.cpp -o learn3 -O2
	g++ learn4.cpp -o learn4 -O2
	g++ learn5.cpp -o learn5 -O2

clean:
	rm platform
	rm agent1
	rm agent2
	rm agent3
	rm agent4
	rm agent5
	rm learn1
	rm learn2
	rm learn3
	rm learn4
	rm learn5
	rm result*
	rm helper*
